import SemiCompetitiveAlgo from "./src/algos/semi_competitive";

const config: Config = {
  api: "https://api.bar-rts.com/",
  trackedPlayers: [
    "[DmE]Daniilcola",
    "[GAJ]b0ns",
    "[GAJ]Eddyff1988",
    "[GAJ]farmagio",
    "[GAJWBonX",
    "[FDL]Panikz",
    "[ITA]Sbuffox",
    "ADAW",
    "bio",
    "cacioimperatore",
    "CanestroAnale",
    "Ciabatta",
    "DavideBlade",
    "Denny00",
    "Disprosio",
    "Astroche",
    "Dreamwalk",
    "Flaka",
    "Fra",
    "gabibo",
    "Genny4Real",
    "GrandiCasso",
    "goris",
    "isbad234",
    "ITALIA",
    "JustSomeGuy",
    "kifer",
    "LiveviL",
    "LoScimmiu",
    "Luken",
    "Mavericko",
    "Miksa",
    "Mr_T4k",
    "neuris",
    "NewPlayer1",
    "PerAsperaAdAstra",
    "MrFree",
    "Pitti_Uomo",
    "PocoRiso",
    "PruritoIntimo",
    "pyro066",
    "Sbrock",
    "Screzio",
    "SenzaScopo",
    "soatz",
    "Sult4",
    "TeoPorco",
    "thefallen5555",
    "[smile]ToxicLasagna",
    "Furious_Porcupine",
    "IlBuff3R",
    "Bardack89",
    "Ruggi",
    "GrandiCasso",
    "Madashi",
    "JarmenEnza",
    "Uniforce",
    "ANTIHUMAN",
    "Ale1199",
    "Gattone01",
    "doxop",
    "FarmerKit",
    "SuperShallo338",
    "[ETC]Ralos90",
    "[ETC]ThePunisher8731",
    "Malsi",
    "IceMak",
    "Dempsy",
    "Shimada",
    "Babbux",
    "Wildcat",
    "jettop",
    "Madashi",
    "mark_Karl",
    "Prese3",
    "Stelfirio",
    "[SG]CMDR_Zod",
  ],
  usedAlgorithm: SemiCompetitiveAlgo,
  dataRetrivalMethod: "api",
};

export default config;

interface Config {
  dataRetrivalMethod: "api" | "dumpDb";
  api: string;
  trackedPlayers: string[];
  usedAlgorithm: Function;
}
